version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/fakebook
hooks:
  # BeforeInstall:
  #   - location: beforeinstall.sh
  #     timeout: 100
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100