version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/fakebook
hooks:
  # BeforeInstall:
  #   - location: beforeinstall.sh
  #     timeout: 100
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 100